using System.Collections.Generic;

namespace zMoneyWinX.ViewModel
{
    public static class IconSet
    {
        public static List<string> getIconSet()
        {
            List<string> res = new List<string>();
            res.Add("0000_none");
            res.Add("1001_bunch_ingredients");
            res.Add("1002_diningroom");
            res.Add("2001_beer");
            res.Add("2002_dancing");
            res.Add("2003_film_reel");
            res.Add("2004_champagne");
            res.Add("2005_birthday");
            res.Add("2006_candy");
            res.Add("2007_controller");
            res.Add("2008_books");
            res.Add("2501_hand_biceps");
            res.Add("2502_football");
            res.Add("2503_swimming");
            res.Add("2504_ping_pong");
            res.Add("2505_paint_palette");
            res.Add("3001_bus2");
            res.Add("3002_cars");
            res.Add("3003_bicycle");
            res.Add("3003_gas_station");
            res.Add("3004_motorcycle");
            res.Add("3004_taxi");
            res.Add("3005_train");
            res.Add("3501_gas_station");
            res.Add("3502_work");
            res.Add("4001_airport");
            res.Add("4002_beach");
            res.Add("4501_phone2");
            res.Add("5001_coat");
            res.Add("5002_shoe_woman");
            res.Add("5003_portrait_mode");
            res.Add("5004_barbers_scissors");
            res.Add("5400_garage");
            res.Add("5401_exterior");
            res.Add("5402_bath");
            res.Add("5403_broom");
            res.Add("5501_armchair");
            res.Add("5502_retro_tv");
            res.Add("5503_electrical");
            res.Add("5504_electric_teapot");
            res.Add("5505_laptop");
            res.Add("5506_mobile");
            res.Add("5507_lamp");
            res.Add("5508_coffee_maker");
            res.Add("5509_camera");
            res.Add("5510_potted_plant");
            res.Add("6001_children");
            res.Add("6002_stroller");
            res.Add("6003_carousel");
            res.Add("6003_man");
            res.Add("6004_woman");
            res.Add("6501_doctor_suitecase");
            res.Add("6502_pill");
            res.Add("6503_doctor");
            res.Add("6505_smoking");
            res.Add("7001_gift");
            res.Add("7002_literature");
            res.Add("7501_tree");
            res.Add("7502_campfire");
            res.Add("7503_flower");
            res.Add("7901_cat");
            res.Add("7902_dog");
            res.Add("7903_fish");
            res.Add("8001_question");
            res.Add("8002_globe");
            res.Add("8003_internet_explorer");
            res.Add("8004_musical");
            res.Add("8501_factory");
            res.Add("8502_training");
            res.Add("8503_handshake");
            res.Add("9001_cash_receiving");
            res.Add("9002_money_bag");
            res.Add("9003_banknotes");
            res.Add("9004_wallet");
            res.Add("9005_gold_bars");
            res.Add("9006_safe");
            return res;
        }
    }
}
